---
- name: Ensure python3-six is installed on all Proxmox nodes
  hosts: proxmox
  become: yes
  gather_facts: false
  tasks:
    - name: Install python3-six
      apt:
        name: python3-six
        state: present
        update_cache: yes
