---
- name: List all VMs from the entire Proxmox cluster
  hosts: localhost
  gather_facts: false
  vars:
    proxmox_host: "10.200.7.10"         # One node's API endpoint is enough for cluster-wide query
    proxmox_user: "ansible@pve"
    proxmox_token_id: "ansible-token"
    proxmox_token_secret: "{{ ansible_password }}"
    validate_certs: false

  tasks:
    - name: Get all cluster resources
      community.proxmox.proxmox_vm_info:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        validate_certs: "{{ validate_certs }}"
        type: qemu          # ensures we only get VMs, not containers
      register: vm_info

    - name: Print VMs grouped by node
      debug:
        msg: |
          {% for node in vm_info.proxmox_vms | groupby('node') %}
          Node: {{ node.0 }}
          {% for vm in node.1 %}
            VMID: {{ vm.vmid }} | Name: {{ vm.name }} | Status: {{ vm.status }}
          {% endfor %}
          {% endfor %}
