---
- name: Verify Proxmox API authentication across all nodes
  hosts: localhost
  gather_facts: false
  vars:
    proxmox_host: "10.200.7.10"
    proxmox_user: "ansible@pve!ansible-token"
    proxmox_token: "{{ ansible_password }}"  # Store secret in AAP credentials
    validate_certs: false

  tasks:
    - name: Get all VMs from entire Proxmox cluster
      community.proxmox.proxmox_vm_info:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_user }}"
        api_token_secret: "{{ proxmox_token }}"
        validate_certs: "{{ validate_certs }}"
      register: vm_info

    - name: Print summary of all VMs by node
      debug:
        var: vm_info
