---
- name: List all VMs from the entire Proxmox cluster
  hosts: localhost
  gather_facts: false
  vars:
    proxmox_host: "10.200.7.10"
    proxmox_user: "ansible@pve"
    proxmox_token_id: "ansible-token"
    proxmox_token_secret: "{{ ansible_password }}"
    validate_certs: false

  tasks:
    - name: Get all cluster resources directly
      uri:
        url: "https://{{ proxmox_host }}:8006/api2/json/cluster/resources"
        method: GET
        headers:
          Authorization: "PVEAPIToken={{ proxmox_user }}!{{ proxmox_token_id }}={{ proxmox_token_secret }}"
        validate_certs: no
      register: cluster_resources
      failed_when: cluster_resources.status != 200

    - name: Extract QEMU VM list
      set_fact:
        vms: "{{ cluster_resources.json.data | selectattr('type','equalto','qemu') | list }}"

    - name: Print VMs grouped by node
      debug:
        msg: |
          {% for node, node_vms in vms | groupby('node') %}
          Node: {{ node }}
          {% for vm in node_vms %}
            VMID: {{ vm.vmid }} | Name: {{ vm.name }} | Status: {{ vm.status }}
          {% endfor %}
          {% endfor %}
